# GoReleaser configuration for codebak
# Run with: goreleaser release --clean

version: 2

before:
  hooks:
    - go mod tidy
    - go mod verify

builds:
  - id: codebak
    main: ./cmd/codebak
    binary: codebak
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - linux
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X main.version={{.Version}}

archives:
  - id: default
    format: tar.gz
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    files:
      - README.md
      - LICENSE*

checksum:
  name_template: "checksums.txt"
  algorithm: sha256

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^chore:"
      - Merge pull request
      - Merge branch

release:
  github:
    owner: mcdonaldj
    name: codebak
  draft: false
  prerelease: auto
  name_template: "v{{.Version}}"
